version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tienda
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: [red_practica4]

  app:
    build: ./app
    image: imagen_practica4
    depends_on: [postgres]
    ports:
      - "8080:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: tienda
      DB_HOST: postgres
    networks: [red_practica4]

networks:
  red_practica4:
    driver: bridge

volumes:
  pg_data:
